/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.util.ArrayList;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import trabajopractico5.Contacto;


      import javax.swing.JTextField;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.DefaultListModel;


/**
 *
 * @author Sutara
 */
public class BuscarTelefonoApellido extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarTelefonoApellido
     * 
     * 
     * 
     * 
     * 
     * 
     * 
     * 
     * 
     * 
     */
     private DefaultTableModel modelo;
     
     private DefaultListModel modeloLista;
    
    
    public BuscarTelefonoApellido() {
        initComponents();
        
         modelo =new DefaultTableModel();
         
         modeloLista=new DefaultListModel();
        
      //   buscarTel();
         
            armarCabeceraTabla();
 
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtApeBuscarTelefono = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btnSalirBuscarTelefono = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Buscar Teléfono por Apellido");

        jLabel2.setText("Apellido:");

        txtApeBuscarTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApeBuscarTelefonoKeyTyped(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Apellido", "Nombre", "Direccion", "Ciudad", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jScrollPane2.setViewportView(jList1);

        btnSalirBuscarTelefono.setText("Salir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(309, 309, 309))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSalirBuscarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtApeBuscarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 13, Short.MAX_VALUE)))
                        .addGap(30, 30, 30))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtApeBuscarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnSalirBuscarTelefono)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApeBuscarTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApeBuscarTelefonoKeyTyped
       
  
      
      
          
         
        
        
        
// ... En un método donde creas tus componentes ...
JTextField txtSoloNumeros = new JTextField();

txtApeBuscarTelefono.addKeyListener(new KeyAdapter() {
    @Override
    public void keyTyped(KeyEvent e) {
      
                filtrarLista();
            }
        });

        // Initial list population
        filtrarLista();
    }

    private void filtrarLista() {
        String textoBusqueda = txtApeBuscarTelefono.getText();
        modeloLista.clear(); 

        
        if (textoBusqueda.isEmpty()) {
            
            
            
            
            
            for (Map.Entry<Long, Contacto> entry : FrmMenuPrincipal.directorio.mostrarDirectorioTelefonico().entrySet()) {
                Long key = entry.getKey();
                Contacto value = entry.getValue();
                
                modeloLista.addElement(value.getNombre() + value.getApellido());
                
                
                               
            }
            
                             
               
            }
          
        

      
    }//GEN-LAST:event_txtApeBuscarTelefonoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalirBuscarTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtApeBuscarTelefono;
    // End of variables declaration//GEN-END:variables



// CONTINUAR EL METODO.. 

//llenarClientesApellido
    
  /*  
    public void buscarTel(){

    


            for (Map.Entry<Long, Contacto> en : FrmMenuPrincipal.directorio.mostrarDirectorioTelefonico().entrySet()) {
                Object key = en.getKey();
                Object value = en.getValue();
                
                
                if(en.getValue().getApellido().equalsIgnoreCase(txtApeBuscarTelefono)){
               
                
                
                }
                
                
                
            }

}

*/

 private void armarCabeceraTabla(){
    ArrayList <Object> mod = new ArrayList();
    mod.add("DNI");
   mod.add("Apellido");
    mod.add("Nombre");
    mod.add("Direccion");
    mod.add("Ciudad");
    mod.add("Telefono");
     for (Object aux : mod) {
         modelo.addColumn(aux);
     }
     jTable1.setModel(modelo);
}
 
 
  
 private void llenarTabla(){
    borrarFilas();
    String ciudad = (String) txtApeBuscarTelefono.getSelectedText();
        for (Map.Entry<Long,Contacto> aux : FrmMenuPrincipal.directorio.mostrarDirectorioTelefonico().entrySet()) {
            if(aux.getValue().getCiudad().equals(ciudad)){
                       
                modelo.addRow(new Object[]{aux.getValue().getDni(),aux.getValue().getApellido(),aux.getValue().getNombre(),aux.getValue().getDireccion(),aux.getValue().getCiudad(),aux.getKey()});
                
                
                
                
                
      }  
  }
 
 }
 
 private void borrarFilas(){
     int numFilas= modelo.getRowCount() -1;
     for (int i = numFilas; i >= 0; i--) {
         modelo.removeRow( i );
         
     }
 }
 
 
 
 
 
  

}

